from enum import Enum


class OrderStatus(str, Enum):
    CREATED = "created"
    ATTEMPTED = "attempted"
    PAID = "paid"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


class PaymentAttemptStatus(str, Enum):
    CREATED = "created"
    AUTHORIZED = "authorized"
    CAPTURED = "captured"
    FAILED = "failed"
    REFUNDED = "refunded"


class OpportunityStatus(str, Enum):
    DETECTED = "DETECTED"
    SCORING = "SCORING"
    IGNORED = "IGNORED"
    EVALUATING = "EVALUATING"
    POLICY_GATING = "POLICY_GATING"
    EXECUTING = "EXECUTING"
    INTERVENED = "INTERVENED"
    ACTION_FAILED = "ACTION_FAILED"
    RETRY_PENDING = "RETRY_PENDING"
    RECOVERED = "RECOVERED"
    PARTIALLY_RECOVERED = "PARTIALLY_RECOVERED"
    EXPIRED = "EXPIRED"
    ESCALATED = "ESCALATED"
    CLOSED_UNRECOVERED = "CLOSED_UNRECOVERED"


class RecoveryActionType(str, Enum):
    CREATE_RECOVERY_PAYMENT_LINK = "CREATE_RECOVERY_PAYMENT_LINK"
    CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"  # Canonical alias
    SCHEDULE_MANDATE_RETRY = "SCHEDULE_MANDATE_RETRY"
    CUSTOMER_REMINDER_SMS = "CUSTOMER_REMINDER_SMS"
    ESCALATE_TO_MERCHANT = "ESCALATE_TO_MERCHANT"
    NO_ACTION = "NO_ACTION"
    NO_ACTION_CLOSE = "NO_ACTION_CLOSE"  # Canonical alias


class DiagnosisCategory(str, Enum):
    TRANSIENT_PAYMENT_FAILURE = "TRANSIENT_PAYMENT_FAILURE"
    CUSTOMER_ACTION_REQUIRED = "CUSTOMER_ACTION_REQUIRED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    PAYMENT_METHOD_ISSUE = "PAYMENT_METHOD_ISSUE"
    PERMANENT_PAYMENT_FAILURE = "PERMANENT_PAYMENT_FAILURE"
    UNKNOWN = "UNKNOWN"


class ActionExecutionStatus(str, Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    SUCCESS = "SUCCEEDED"  # Canonical alias
    FAILED = "FAILED"
    AMBIGUOUS = "AMBIGUOUS"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class ProviderErrorCategory(str, Enum):
    TRANSIENT_PROVIDER_ERROR = "TRANSIENT_PROVIDER_ERROR"
    PERMANENT_PROVIDER_ERROR = "PERMANENT_PROVIDER_ERROR"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    TIMEOUT = "TIMEOUT"
    AMBIGUOUS = "AMBIGUOUS"


class ActorType(str, Enum):
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
    POLICY_ENGINE = "POLICY_ENGINE"
    EXECUTOR = "EXECUTOR"
    MERCHANT_USER = "MERCHANT_USER"
